name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build CLI tools
        run: |
          cargo build --release --bin 等一下 --bin 寸止 ${{ matrix.args }}

      - name: Create CLI package
        shell: bash
        run: |
          mkdir -p cli-package
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            cp target/release/等一下.exe cli-package/
            cp target/release/寸止.exe cli-package/
            cd cli-package
            7z a ../cunzhi-cli-${{ github.ref_name }}-windows.zip *
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.args }}" == *"aarch64"* ]]; then
              cp target/aarch64-apple-darwin/release/等一下 cli-package/
              cp target/aarch64-apple-darwin/release/寸止 cli-package/
              cd cli-package
              tar -czf ../cunzhi-cli-${{ github.ref_name }}-macos-aarch64.tar.gz *
            else
              cp target/x86_64-apple-darwin/release/等一下 cli-package/
              cp target/x86_64-apple-darwin/release/寸止 cli-package/
              cd cli-package
              tar -czf ../cunzhi-cli-${{ github.ref_name }}-macos-x86_64.tar.gz *
            fi
          else
            cp target/release/等一下 cli-package/
            cp target/release/寸止 cli-package/
            cd cli-package
            tar -czf ../cunzhi-cli-${{ github.ref_name }}-linux.tar.gz *
          fi

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Release ${{ github.ref_name }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          includeDebug: false
          includeRelease: true
          releaseFiles: |
            cunzhi-cli-*.tar.gz
            cunzhi-cli-*.zip
